### ISSUE TITLE
Cursor disappears after renaming

### ISSUE THREAD

**Issue by sprt** [zmb3/gorename#14]
Repro:
- Place cursor on identifier
- Press Alt+R and rename the identifier
- Cursor disappears, forced to click somewhere to bring it back

**Comment by joefitzgerald** [comment]
@zmb3 I have code that saves and restores the cursor in `gofmt`. Might want to reuse?
- https://github.com/joefitzgerald/gofmt/blob/d271dcb468e1f894cf5948987b9c570ec50c195a/lib/formatter.js#L289
- https://github.com/joefitzgerald/gofmt/blob/d271dcb468e1f894cf5948987b9c570ec50c195a/lib/formatter.js#L305-L307

**Comment by zmb3** [comment]
You betcha.  I'll get this in ASAP (today or tomorrow).

On second thought, this is a little trickier for me, because I'm not replacing the contents of the buffer like you do with `gofmt`.  `gorename` modifies the files on disk, and then Atom refreshes when it detects they've changed.  I'd have to restore the cursor _after_ this happens, and I"m not sure Atom has the hooks in for me to detect this.

The other option would be to invoke `gorename` with the `-d` option, which displays diffs instead of modifying the files (and then we'd have to manually update those files).
