### ISSUE TITLE
Please can you update your readme with the correct keymappings

### ISSUE THREAD

**Issue by duncwinn** [zmb3/gorename#3]
Nice visual but it does not show me how to use it.

**Comment by zmb3** [comment]
Thanks, I will definitely add the keymappings to the readme.  Part of the reason I haven't done this is because I haven't settled on what one to use.  The current setting (ctrl+shift+r) is also used by the tree view plugin, so I want to pick something different.  I have to do a little research to see if there's a commonly accepted keyboard shortcut for renaming things in other editors/packages.

FWIW you can also invoke the rename command by right clicking in the editor and selecting "rename symbol under cursor (gorename)."

I haven't actually published a release of this yet, so if you installed it from `apm` you just got a skeleton that doesn't do anything.  I hope to get a release out this week. In the meantime if you wanted to play with it you can `apm develop gorename` and then start Atom with the `-d` flag to load dev packages.

**Comment by micahthomas** [comment]
alt+r is a pretty common rename shortcut

**Comment by zmb3** [comment]
Thanks @micahthomas .  `alt+r` it is.

I'm closing this issue now (fixed with ca7435d).
